/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_lanza_HiJNI */

#ifndef _Included_io_lanza_HiJNI
#define _Included_io_lanza_HiJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_lanza_HiJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_lanza_HiJNI_sayHello(JNIEnv *, jobject);

/*
 * Class:     io_lanza_HiJNI
 * Method:    makePersonString
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_lanza_HiJNI_makePersonString(JNIEnv *,
                                                               jobject, jstring,
                                                               jint);

#ifdef __cplusplus
}
#endif
#endif
